---
collections:
  - name: devsec.hardening
    type: git
    source: https://github.com/dev-sec/ansible-collection-hardening
    version: 9.0.1

  - name: hetzner.hcloud
    type: git
    source: https://github.com/ansible-collections/hetzner.hcloud
    version: 3.0.0
