---
- name: install docker
  apt:
    name:
      - docker.io
    state: present
    update_cache: yes
    cache_valid_time: 600
  become: true

- name: configure docker

# TODO:
# {
#     "ipv6": true,
#     "fixed-cidr-v6": "fd00:0:0:1::/64",
#     "experimental": true,
#     "ip6tables": true
# }

# TODO reload docker config if changed

- name: remove docker-compose
  apt:
    name:
      - docker-compose
    state: absent
    autoremove: yes
    update_cache: yes
    cache_valid_time: 600
  become: true

- name: install docker-compose
  get_url:
    url : https://github.com/docker/compose/releases/download/v2.14.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'a+rx'
  become: true

- name: enable / start docker
  systemd:
    state: started
    enabled: yes
    name: docker
  become: true
