---
- name: Add docker group
  group:
    name: docker
    state: present
  become: true

- name: Add admin group
  group:
    name: admin
    state: present
  become: true

- name: Add admin user
  user:
    name: admin
    comment: ownCloud Administrator
    create_home: yes
    append: yes
    groups:
      - admin
      - sudo
      - docker
    shell: /bin/bash
    state: present
  become: true

- name: passwordless sudo for sudo group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "sudo ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
  become: true

- name: passwordless sudo for admin group
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%admin"
    line: "admin ALL=(ALL) NOPASSWD:ALL"
    validate: "visudo -cf %s"
  become: true
